// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwgjsrwhgjmiiafqtjcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3Z2pzcndoZ2ptaWlhZnF0amNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwOTg2MzQsImV4cCI6MjA3NzY3NDYzNH0.ptK7Etqp8IApwb1fT3LFS7jwRq_TgIDi8iWblzqjC1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});